import { readdirSync, statSync } from 'fs';
import { join, relative, extname } from 'path';
import type { Route } from '@speedjs/router';

export interface ScanOptions {
  routesDir: string;
  appDir: string;
}

export interface ScanResult {
  routes: Route[];
  errors: string[];
}

export function scanRoutes(options: ScanOptions): ScanResult {
  const { routesDir, appDir } = options;
  const routes: Route[] = [];
  const errors: string[] = [];

  try {
    scanDirectory(routesDir, routesDir, appDir, routes, errors);
  } catch (error) {
    errors.push(error instanceof Error ? error.message : 'Unknown error scanning routes');
  }

  return { routes, errors };
}

function scanDirectory(
  dir: string,
  routesDir: string,
  appDir: string,
  routes: Route[],
  errors: string[]
): void {
  const entries = readdirSync(dir);

  for (const entry of entries) {
    const fullPath = join(dir, entry);
    const stat = statSync(fullPath);

    if (stat.isDirectory()) {
      scanDirectory(fullPath, routesDir, appDir, routes, errors);
    } else if (stat.isFile() && isRouteFile(entry)) {
      const route = createRoute(fullPath, routesDir, appDir);
      if (route) {
        routes.push(route);
      }
    }
  }
}

function isRouteFile(filename: string): boolean {
  const ext = extname(filename);
  return ext === '.tsx' || ext === '.ts' || ext === '.jsx' || ext === '.js';
}

function createRoute(filePath: string, routesDir: string, appDir: string): Route | null {
  const relativePath = relative(routesDir, filePath);
  const routePath = filePathToRoutePath(relativePath);
  const file = relative(appDir, filePath);

  return {
    id: routePath.replace(/\//g, '-') || 'index',
    path: routePath,
    file,
  };
}

function filePathToRoutePath(filePath: string): string {
  // Remove extension
  const withoutExt = filePath.replace(/\.(tsx?|jsx?)$/, '');

  // Handle index files
  if (withoutExt === 'index') {
    return '/';
  }

  // Handle [param] dynamic segments
  const path = withoutExt
    .replace(/\[(\w+)\]/g, ':$1') // [id] -> :id
    .replace(/\[\.\.\.(\w+)\]/g, ':$1*'); // [...slug] -> :slug*

  // Handle nested index files
  if (path.endsWith('/index')) {
    return path.slice(0, -6) || '/';
  }

  return '/' + path;
}

export function generateRouteManifest(routes: Route[]): string {
  return `// This file is auto-generated by Speed.js
import type { RouteManifest } from '@speedjs/router';

export const routes: RouteManifest = {
  routes: ${JSON.stringify(routes, null, 2)}
};
`;
}
